sudo: false
language: ruby
rvm:
  - 2.5.0
services:
  - mysql
  - postgresql
before_install:
  - gem install bundler -v 1.16.1
  - mysql -e 'CREATE DATABASE temporalis_test;'
  - psql -c 'CREATE DATABASE temporalis_test;' -U postgres
env:
  - MYSQL_DATABASE_URL=mysql2://travis@localhost/temporalis_test POSTGRESQL_DATABASE_URL=postgresql://postgres@localhost/temporalis_test SQLITE3_DATABASE_URL="sqlite3::memory:" DATABASES_TO_TEST="sqlite3,mysql,postgresql"
cache:
  - bundler
notifications:
  email:
    - me@markabramov.me
